export const _ = {
  first: require('lodash/first'),
  last: require('lodash/last'),
  filter: require('lodash/filter'),
  isEmpty: require('lodash/isEmpty'),
  map: require('lodash/map'),
  findIndex: require('lodash/findIndex'),
  omit: require('lodash/omit'),
  toNumber: require('lodash/toNumber'),
  padStart: require('lodash/padStart'),
  toString: require('lodash/toString'),
  maxBy: require('lodash/maxBy'),
  round: require('lodash/round'),
  merge: require('lodash/merge'),
  includes: require('lodash/includes'),
  split: require('lodash/split'),
  find: require('lodash/find'),
  isArray: require('lodash/isArray'),
  forEach: require('lodash/forEach'),
  values: require('lodash/values'),
  trim: require('lodash/trim'),
  reject: require('lodash/reject'),
  snakeCase: require('lodash/snakeCase'),
  isBoolean: require('lodash/isBoolean'),
  toLower: require('lodash/toLower'),
  keys: require('lodash/keys'),
  isObject: require('lodash/isObject'),
  join: require('lodash/join'),
  uniq: require('lodash/uniq'),
  replace: require('lodash/replace'),
  isString: require('lodash/isString'),
  isPlainObject: require('lodash/isPlainObject'),
  transform: require('lodash/transform'),
  has: require('lodash/has'),
  isEqual: require('lodash/isEqual'),
  forOwn: require('lodash/forOwn'),
  remove: require('lodash/remove'),
  reduce: require('lodash/reduce'),
  assign: require('lodash/assign'),
  pick: require('lodash/pick'),
  cloneDeep: require('lodash/cloneDeep'),
  findLastIndex: require('lodash/findLastIndex'),
  orderBy: require('lodash/orderBy'),
}

export default _